version: '3.7'

services:
  db:
    container_name: nextwitch-postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextwitch-backend

  redis:
    container_name: nextwitch-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - nextwitch-backend

volumes:
  postgres_data:
  redis_data:

networks:
  nextwitch-backend:
